### ISSUE TITLE
同一个人多个群绑定会绑定失败，数据库内也没有多添加的群的字段

### ISSUE THREAD

**Issue by axlmly** [MomoiAiri/Koishi-Plugin-Steam-Friend-Status#3]
以及直接使用绑定steam会日志会报错，而不是提示用户缺少输入。

**Comment by MomoiAiri** [comment]
第一个问题经过排查如果你使用的是satori/red适配器，会出现无法获取到用户名情况，而写入数据库时会校验用户名（前两天还能正常来着，今天晚上我也出现这个问题了），目前已经将校验部分修改，没有用户名时直接使用用户ID填充，所以暂时推荐使用steam昵称来播报。第二个问题已解决。

**Comment by MomoiAiri** [comment]
补充：当用户在群内改过群昵称时chronocat会无法获取到QQ昵称，因而导致了绑定失败，如果你使用的平台正式cc的话就是这个原因了
