### ISSUE TITLE
重启后看看steam无法渲染头像，是否考虑把看看steam和更新steam两个指令合并

### ISSUE THREAD

**Issue by axlmly** [MomoiAiri/Koishi-Plugin-Steam-Friend-Status#4]

**Comment by axlmly** [comment]
运行一段时间后日志出现![-12605a25adc1e374.jpg](https://github.com/MomoiAiri/Koishi-Plugin-Steam-Friend-Status/assets/41771421/cfe520ca-4e8b-474c-ac20-fa6b4ae746c5)

**Comment by MomoiAiri** [comment]
这个问题是由于更新插件会清空lib中的资源，已在新版本中解决
